### ISSUE TITLE
Error copying assets

### ISSUE THREAD

**Issue by wasa4587** [co2-git/reactors-cli#9]
After `reactors init MyApp`

Copy assets
cp: /usr/local/lib/node_modules/reactors-cli/templates/assets/*.png: No such file or directory
Error: Got status 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/reactors-cli/dist/util/exec.js:29:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
Error
Error: Got status 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/reactors-cli/dist/util/exec.js:29:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

it's kind of weird because that path exists

drwxr-xr-x  8 nobody  staff  272 Feb  7 10:43 /usr/local/lib/node_modules/reactors-cli/templates/assets/

**Comment by co2-git** [comment]
Can you try again with v1.3.6 or above?

**Comment by wasa4587** [comment]
yup it worked 👍
